[package]
name = "bitmap-indexer"
version = "0.1.0"
edition = "2021"

[dependencies]
ordinals = { git = "https://github.com/ordinals/ord", branch = "master" }
bitcoin = "0.32.3"
rusqlite = "0.32.1"
serde = { version = "1.0.210", features = ["derive"] }
serde_cbor = "0.11.2"
serde_json = "1.0.128"
reqwest = { version = "0.12.7", features = ["json"] }
libp2p = { version = "0.53.2", features = ["tcp", "tokio", "gossipsub", "kad"] }
config = "0.14.0"
log = "0.4.22"
env_logger = "0.11.5"
rayon = "1.10.0"
num_cpus = "1.16.0"
tokio = { version = "1.40.0", features = ["full"] }
